/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWantedRouteImport } from './routes/_layout/wanted'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRssRouteImport } from './routes/_layout/rss'
import { Route as LayoutLogsRouteImport } from './routes/_layout/logs'
import { Route as LayoutDownloadsRouteImport } from './routes/_layout/downloads'
import { Route as LayoutCalendarRouteImport } from './routes/_layout/calendar'
import { Route as LayoutMediaIndexRouteImport } from './routes/_layout/media/index'
import { Route as LayoutMediaScanRouteImport } from './routes/_layout/media/scan'
import { Route as LayoutMediaImportRouteImport } from './routes/_layout/media/import'
import { Route as LayoutMediaAddRouteImport } from './routes/_layout/media/add'
import { Route as LayoutMediaIdRouteImport } from './routes/_layout/media/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWantedRoute = LayoutWantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRssRoute = LayoutRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLogsRoute = LayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDownloadsRoute = LayoutDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarRoute = LayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMediaIndexRoute = LayoutMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMediaScanRoute = LayoutMediaScanRouteImport.update({
  id: '/media/scan',
  path: '/media/scan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMediaImportRoute = LayoutMediaImportRouteImport.update({
  id: '/media/import',
  path: '/media/import',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMediaAddRoute = LayoutMediaAddRouteImport.update({
  id: '/media/add',
  path: '/media/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMediaIdRoute = LayoutMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof LayoutCalendarRoute
  '/downloads': typeof LayoutDownloadsRoute
  '/logs': typeof LayoutLogsRoute
  '/rss': typeof LayoutRssRoute
  '/settings': typeof LayoutSettingsRoute
  '/wanted': typeof LayoutWantedRoute
  '/media/$id': typeof LayoutMediaIdRoute
  '/media/add': typeof LayoutMediaAddRoute
  '/media/import': typeof LayoutMediaImportRoute
  '/media/scan': typeof LayoutMediaScanRoute
  '/media/': typeof LayoutMediaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof LayoutCalendarRoute
  '/downloads': typeof LayoutDownloadsRoute
  '/logs': typeof LayoutLogsRoute
  '/rss': typeof LayoutRssRoute
  '/settings': typeof LayoutSettingsRoute
  '/wanted': typeof LayoutWantedRoute
  '/': typeof LayoutIndexRoute
  '/media/$id': typeof LayoutMediaIdRoute
  '/media/add': typeof LayoutMediaAddRoute
  '/media/import': typeof LayoutMediaImportRoute
  '/media/scan': typeof LayoutMediaScanRoute
  '/media': typeof LayoutMediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/calendar': typeof LayoutCalendarRoute
  '/_layout/downloads': typeof LayoutDownloadsRoute
  '/_layout/logs': typeof LayoutLogsRoute
  '/_layout/rss': typeof LayoutRssRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/wanted': typeof LayoutWantedRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/media/$id': typeof LayoutMediaIdRoute
  '/_layout/media/add': typeof LayoutMediaAddRoute
  '/_layout/media/import': typeof LayoutMediaImportRoute
  '/_layout/media/scan': typeof LayoutMediaScanRoute
  '/_layout/media/': typeof LayoutMediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/downloads'
    | '/logs'
    | '/rss'
    | '/settings'
    | '/wanted'
    | '/media/$id'
    | '/media/add'
    | '/media/import'
    | '/media/scan'
    | '/media/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/downloads'
    | '/logs'
    | '/rss'
    | '/settings'
    | '/wanted'
    | '/'
    | '/media/$id'
    | '/media/add'
    | '/media/import'
    | '/media/scan'
    | '/media'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/calendar'
    | '/_layout/downloads'
    | '/_layout/logs'
    | '/_layout/rss'
    | '/_layout/settings'
    | '/_layout/wanted'
    | '/_layout/'
    | '/_layout/media/$id'
    | '/_layout/media/add'
    | '/_layout/media/import'
    | '/_layout/media/scan'
    | '/_layout/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wanted': {
      id: '/_layout/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof LayoutWantedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rss': {
      id: '/_layout/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof LayoutRssRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/logs': {
      id: '/_layout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LayoutLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/downloads': {
      id: '/_layout/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof LayoutDownloadsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar': {
      id: '/_layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LayoutCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/media/': {
      id: '/_layout/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof LayoutMediaIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/media/scan': {
      id: '/_layout/media/scan'
      path: '/media/scan'
      fullPath: '/media/scan'
      preLoaderRoute: typeof LayoutMediaScanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/media/import': {
      id: '/_layout/media/import'
      path: '/media/import'
      fullPath: '/media/import'
      preLoaderRoute: typeof LayoutMediaImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/media/add': {
      id: '/_layout/media/add'
      path: '/media/add'
      fullPath: '/media/add'
      preLoaderRoute: typeof LayoutMediaAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/media/$id': {
      id: '/_layout/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof LayoutMediaIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCalendarRoute: typeof LayoutCalendarRoute
  LayoutDownloadsRoute: typeof LayoutDownloadsRoute
  LayoutLogsRoute: typeof LayoutLogsRoute
  LayoutRssRoute: typeof LayoutRssRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWantedRoute: typeof LayoutWantedRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMediaIdRoute: typeof LayoutMediaIdRoute
  LayoutMediaAddRoute: typeof LayoutMediaAddRoute
  LayoutMediaImportRoute: typeof LayoutMediaImportRoute
  LayoutMediaScanRoute: typeof LayoutMediaScanRoute
  LayoutMediaIndexRoute: typeof LayoutMediaIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCalendarRoute: LayoutCalendarRoute,
  LayoutDownloadsRoute: LayoutDownloadsRoute,
  LayoutLogsRoute: LayoutLogsRoute,
  LayoutRssRoute: LayoutRssRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWantedRoute: LayoutWantedRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMediaIdRoute: LayoutMediaIdRoute,
  LayoutMediaAddRoute: LayoutMediaAddRoute,
  LayoutMediaImportRoute: LayoutMediaImportRoute,
  LayoutMediaScanRoute: LayoutMediaScanRoute,
  LayoutMediaIndexRoute: LayoutMediaIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
