import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { contentType } from "../src/http/shared/route-fs.ts";

const apiRoot = fileURLToPath(new URL("../", import.meta.url));
const webDistRoot = path.resolve(apiRoot, "../web/dist");
const drizzleRoot = path.resolve(apiRoot, "drizzle");
const generatedRoot = path.resolve(apiRoot, "src/generated");

await mkdir(generatedRoot, { recursive: true });

const webAssets = await collectFiles(webDistRoot);
const migrationFiles = (await collectFiles(drizzleRoot)).filter((filePath) =>
  filePath.endsWith(".sql"),
);

await writeFile(
  path.join(generatedRoot, "embedded-web-assets.ts"),
  await renderEmbeddedWebAssetsModule(webAssets),
);

await writeFile(
  path.join(generatedRoot, "embedded-drizzle-migrations.ts"),
  await renderEmbeddedMigrationModule(migrationFiles),
);

async function renderEmbeddedMigrationModule(filePaths: readonly string[]) {
  const entries = await Promise.all(
    [...filePaths].toSorted().map(async (filePath) => {
      const relativePath = toPosixPath(path.relative(drizzleRoot, filePath));
      const migrationName = relativePath.replace(/\.sql$/u, "");
      const sql = await readFile(filePath, "utf8");
      const statements = splitMigrationStatements(sql);

      return [migrationName, statements] as const;
    }),
  );

  const lines = [
    "// Generated by tools/generate-embedded-artifacts.ts. Do not edit manually.",
    "",
    "export type EmbeddedDrizzleMigrations = Record<string, readonly string[]>;",
    "",
    "export const embeddedDrizzleMigrations = {",
  ];

  for (const [migrationName, statements] of entries) {
    lines.push(`  ${JSON.stringify(migrationName)}: [`);
    for (const statement of statements) {
      lines.push(`    ${JSON.stringify(statement)},`);
    }
    lines.push("  ],");
  }

  lines.push("} as const satisfies EmbeddedDrizzleMigrations;", "");

  return lines.join("\n");
}

async function renderEmbeddedWebAssetsModule(filePaths: readonly string[]) {
  const entries = await Promise.all(
    [...filePaths].toSorted().map(async (filePath) => {
      const relativePath = toPosixPath(path.relative(webDistRoot, filePath));
      const body = await readFile(filePath);

      return {
        bodyBase64: body.toString("base64"),
        contentType: contentType(relativePath),
        relativePath,
        size: body.byteLength,
      };
    }),
  );

  const lines = [
    "// Generated by tools/generate-embedded-artifacts.ts. Do not edit manually.",
    'import { Buffer } from "node:buffer";',
    "",
    "export interface EmbeddedWebAsset {",
    "  readonly body: Uint8Array;",
    "  readonly contentType: string;",
    "  readonly size: number;",
    "}",
    "",
    "export const embeddedWebAssets = {",
    ...entries.flatMap((entry) => [
      `  ${JSON.stringify(entry.relativePath)}: {`,
      `    body: Buffer.from(${JSON.stringify(entry.bodyBase64)}, "base64"),`,
      `    contentType: ${JSON.stringify(entry.contentType)},`,
      `    size: ${entry.size},`,
      "  },",
    ]),
    "} as const satisfies Record<string, EmbeddedWebAsset>;",
    "",
  ];

  return lines.join("\n");
}

async function collectFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const resolvedPath = path.join(root, entry.name);

      if (entry.isDirectory()) {
        return await collectFiles(resolvedPath);
      }

      return entry.isFile() ? [resolvedPath] : [];
    }),
  );

  return files.flat();
}

function splitMigrationStatements(sql: string) {
  const statements = sql
    .split(/--> statement-breakpoint/gu)
    .flatMap((chunk) =>
      chunk.split(
        /\n{2,}(?=(?:CREATE|ALTER|DROP|INSERT|UPDATE|DELETE|PRAGMA|REINDEX|BEGIN|COMMIT|ROLLBACK)\b)/giu,
      ),
    );

  return statements
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);
}

function toPosixPath(filePath: string) {
  return filePath.split(path.sep).join("/");
}
